### ISSUE TITLE
How to supports system path program?

### ISSUE THREAD

**Issue by owensys** [metaescape/org-imagine#1]
I want to use drawio to auto export png file.
my draw.io is installed on system, `executable-find` will found it.
example:
```
#+IMAGINE: draw.io.exe -x -f png -o test.png test.drawio
```

**Comment by metaescape** [comment]
check [8c48aa0](https://github.com/metaescape/org-imagine/commit/8c48aa061c6423f65368c5c6e997034dd42662be)
